CREATE TABLE PRODUCT
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(400) NOT NULL
);

CREATE TABLE SHOPPING_LIST
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(400) NOT NULL
);